[package]
name = "tl-scraper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features=["full"] }
reqwest = { version = "0.11.18", features = ["json"] }
anyhow = "1.0.75"
tracing = "0.1.37"
tracing-subscriber = { version= "0.3.17", features = ["fmt","env-filter", "local-time"] }
serde_json = "1.0.105"
serde = { version = "1.0.183", features = ["serde_derive"] }
chrono =  { version = "0.4.26", features = ["serde"] }
structopt = "0.3.26"
secrecy = { version = "0.8.0", features = ["serde"] }
hyper = "0.14.26"
tracing-log = "0.1.3"
serde_urlencoded = "0.7.1"
tempfile = "3.8.0"
urlencoding = "2.1.3"
rust_decimal = "1.31.0"
futures = "0.3.28"
