[package]
name = "tl-scraper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features=["full"] }
reqwest = { version = "0.11.23", features = ["json"] }
anyhow = { version = "1.0.79", features = ["backtrace"] }
tracing = "0.1.40"
tracing-subscriber = { version= "0.3.18", features = ["fmt","env-filter", "local-time"] }
serde_json = "1.0.111"
serde = { version = "1.0.195", features = ["serde_derive"] }
chrono =  { version = "0.4.31", features = ["serde"] }
secrecy = { version = "0.8.0", features = ["serde"] }
hyper = "1.1.0"
tracing-log = "0.2.0"
serde_urlencoded = "0.7.1"
tempfile = "3.9.0"
urlencoding = "2.1.3"
rust_decimal = "1.33.1"
futures = "0.3.30"
clap = { version = "4.4.18", features = ["derive"] }
axum = { version = "0.7.4", features = ["macros"] }
tokio-util = "0.7.10"
url = "2.5.0"
askama = { version = "0.12.1" }
toml = "0.8.8"
