[package]
name = "tl-scraper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features=["full"] }
reqwest = { version = "0.11.13", features = ["json"] }
anyhow = "1.0.66"
tracing = "0.1.37"
tracing-subscriber = { version= "0.3.7", features = ["fmt","env-filter", "local-time"] }
serde_json = "1.0.89"
serde = { version = "1.0.151", features = ["serde_derive"] }
chrono =  { version = "0.4.19", features = ["serde"] }
structopt = "0.3.26"
secrecy = { version = "0.8.0", features = ["serde"] }
hyper = "0.14.13"
tracing-log = "0.1.3"
serde_urlencoded = "0.7.1"
tempfile = "3.3.0"
urlencoding = "2.1.2"
rust_decimal = "1.27.0"
