[package]
name = "tl-scraper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features=["full"] }
reqwest = { version = "0.11.4", features = ["json"] }
anyhow = "1.0.44"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["serde_derive"] }
chrono =  { version = "0.4.19", features = ["serde"] }
structopt = "0.3.23"
secrecy = { version = "0.8.0", features = ["serde"] }
hyper = "0.14.13"
tracing-log = "0.1.2"
serde_urlencoded = "0.7.0"
tempfile = "3.2.0"
urlencoding = "2.1.0"
rust_decimal = "1.16.0"
