# Borrowed from https://github.com/sfackler/rust-postgres/blob/04bd98e7edb238511661b311c725a176012bca6a/.circleci/config.yml
# Used under MIT license.

version: 2
_anchors:
  restore_dot_cargo: &RESTORE_DOT_CARGO
    restore_cache:
      key: dot-cargo-{{ checksum "~/rust-version" }}
  save_dot_cargo: &SAVE_DOT_CARGO
    save_cache:
      key: dot-cargo-{{ checksum "~/rust-version" }}-{{ .BuildNum }}
      paths:
      - ~/.cargo
  deps_key: &DEPS_KEY
    key: deps-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
  restore_deps: &RESTORE_DEPS
    restore_cache:
      <<: *DEPS_KEY
  save_deps: &SAVE_DEPS
    save_cache:
      <<: *DEPS_KEY
      paths:
      - target

jobs:
  build:
    docker:
      - image: cimg/rust:1.73.0
        environment:
          RUSTFLAGS: -D warnings
    steps:
      - checkout
      - run: rustc --version | tee ~/rust-version
      - run: rustup component add clippy rustfmt
      - run: |
          git config --global user.email "circleci@invalid.example"
          git config --global user.name "CircleCI build"
          git merge --no-edit --no-ff origin/main
      - *RESTORE_DOT_CARGO
      - run: cargo fmt -- --check
      - *RESTORE_DEPS
      - run: cargo install cargo-sort@1.0.9
      - run: cargo sort --check --workspace
      - run: cargo build --locked --all --tests
      - run: cargo clippy --locked --all-targets --all-features -- -D warnings
      - *SAVE_DOT_CARGO
      - *SAVE_DEPS
      - run: cargo test --locked --all
